apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  selector:
    app: vprormq
  ports:
    - port: 15672
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: vprormq-port
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      protocol: TCP
  type: ClusterIP