apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        zone: us-east-1a
      containers:
        - name: db01
          image: azora/vprodb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/*" ]
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0381d4304b1ec15c6
